services:
  app:
    container_name: real-estate-agent
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      NGROK_API_URL: "http://ngrok:4040/api/tunnels"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: real-estate-agent-ngrok
    depends_on:
      - app
    env_file:
      - .env
    command:
      - "http"
      - "app:8000"
      - "--log=stdout"
    ports:
      - "4040:4040"
    restart: unless-stopped
